### ISSUE TITLE
Gem should support deleting documents from index

### ISSUE THREAD

**Issue by id4coding** [vruizext/redisearch-rb#2]
It looks like the redisearch-rb gem lacks support for deleting documents from a created index. Specifically, support for FT.DEL command of RediSearch.

Request implementing this feature in an expedited manner so that the gem, RediSearch, and Redis can be used with a Rails server.

**Comment by vruizext** [comment]
Indeed, the gem lacks of many features. I'll try to catch up with all the missing features in the next 1-2 months.

**Comment by vruizext** [comment]
Fixed in 0917fa2910956e9bfd0e28016fa881183307316c
