### ISSUE TITLE
Need detailed documentation support

### ISSUE THREAD

**Issue by id4coding** [vruizext/redisearch-rb#3]
The current document of redisearch-rb gem shows the usage of, or mentions, the following methods:

1. client initialization
2. create_index
3. add_docs
4. search

However, the source code supports the following methods:

1. client initialization
2. create_index
3. drop_index
4. add_doc
5. search
6. get_by_id
7. info

Request creating a more detailed documentation for all the methods supported so that it becomes easier to use them.

**Comment by vruizext** [comment]
@id4coding Thanks for pointing this. I'll try to complete the doc when I push the next version of the gem

Even though in the `README.md` there aren't examples for every of the methods, if you check the source code, every method is documented. And the three methods that don't have examples are IMHO self-explanatory: `info`, `get_by_id`, `add_doc`
